### ISSUE TITLE
script failed - bigip 13 hotfix2

### ISSUE THREAD

**Issue by matantal1** [F5Networks/f5-cloud-iapps#1]
i already added credentials (access keys) to f5 bigip (system->config>aws) .
then i fired app this iapp to import ec2 instances to my pool. but the script failed.

Oct 31 16:42:46 localhost info scriptd[18940]: 01420004:6: Starting iApp template /Common/f5.service_discovery
Oct 31 16:42:47 localhost info scriptd[18940]: 01420004:6: Ending iApp template /Common/f5.service_discovery
Oct 31 16:42:48 localhost err scriptd[18940]: 014f0013:3: Script (/Common/proxy-app.app/proxy-app_service_discovery_icall_script) generated this Tcl error: (script did not successfully complete: ([]:80 { address [] description [59] connection-limit 0 } []:80 { address [] description [] connection-limit 0 } []:80 { address [] description [] connection-limit 0 } []:80 { address [] description [] connection-limit 0 } jq: error: Cannot index number with string jq: error: Cannot index number with string     while executing "exec /bin/bash -c "NODE_JSON=\$(curl -sku admin: https://localhost:$mgmt_port/mgmt/shared/cloud/nodes?mgmtPort=$mgmt_port\\&cloud=aws\\&memberTag=aws:..."     invoked from within "set members [exec /bin/bash -c "NODE_JSON=\$(curl -sku admin: https://localhost:$mgmt_port/mgmt/shared/cloud/nodes?mgmtPort=$mgmt_port\\&cloud=aws\\&m..." line:4))
Oct 31 16:42:48 localhost err mcpd[6740]: 0107167d:3: Data publisher not found or not implemented when processing request (unknown request), tag (2901).
Oct 31 16:42:48 localhost warning tmsh[32738]: 01420013:4: [api-status-warning] ltm/classification/url-cat-policy is deprecated
Oct 31 16:42:49 localhost warning tmsh[32738]: 01420013:4: [api-status-warning] sys/crypto/ca-bundle-manager is early_access
Oct 31 16:42:49 localhost warning tmsh[32738]: 01420013:4: [api-status-warning] sys/ecm/cloud-provider is deprecated
Oct 31 16:42:49 localhost warning tmsh[32738]: 01420013:4: [api-status-warning] sys/ecm/config is deprecated

any requirments regarding my setup?

**Comment by seattlevine** [comment]
This iApp is not tied to the one that is built in (system->config-aws), so that is unrelated.

Was the f5.service_discovery iapp installed from one of our templates in [f5-aws-cloudformation](https://github.com/F5Networks/f5-aws-cloudformation) or did you install it manually? We do not currently support the iApp being installed manually because the templates are responsible for installing the iApp's dependencies.

It looks as though no pool members were found with the tag you specified. The tag must be either on a VM or a NIC and is case-sensitive. Also pay attention to the public/private selection.

**Comment by matantal1** [comment]
Yes manually installed. this bigip is installed as a box on-prem :)
so installing the CF stack is not relevent.

i tried diffrenet tags both on NIC level or Instance.
when i check my aws trail logs it seems that the access keys provided to the bigip was never used.
it seems that the script fails earlier :\

**Comment by seattlevine** [comment]
This iApp is not intended to work on-prem. The AWS keys are not used in this iApp. AWS authentication is done via EC2 meta-data services which only work when running in AWS.
