### ISSUE TITLE
[RFE] f5-service-discovery to support explicit routing domains

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/f5-cloud-iapps#11]
Hi

We would need that f5-service-discovery supports creating the pool members in a iApp specified routing-domain. This would be a new parameter of the iApp.

Please note that it is not desired to use the TMOS feature of creating the iApp instance in a partition with a default routing domain. This is because ultimately we want to instantiate several service-discovery iApps and be able to refer to the updated pools (each in a different routing domain) by a common virtual server's LTM policy.  In other words, the LTM policy would be in the /Common partition and would not be able to make use of the several pools in the different partitions.
 
Many thanks

       Ulises

PD for the record it is possible to workaround this by using an irule instead of an LTM policy. An iRule in /Common is able to refer to pools in other partitions.  This workaround has been tested it does work but it is not desired because want to make use of LTM policies.

**Comment by wduongf5** [comment]
Thanks for the suggestion, alonsocamaro. I've created an internal issue #1347 to track it.

**Comment by shyawnkarim** [comment]
Closing.

TCL iApps have been deprecated. We recommend using AS3 from the Automation Toolchain.
