### ISSUE TITLE
Cannot Reconfigure iAPP

### ISSUE THREAD

**Issue by hparr** [F5Networks/f5-cloud-iapps#14]
In v 14.0 the iAPP cannot be reconfigured - 01b4002b:3: Client SSL profile (/Common/F5-cloud-logger-CDN.app/F5-cloud-logger-CDN_cred_cssl): the profile has no RSA cert/key pair that can be modified. To add RSA cert/key, please use [cert-key-chain add].

**Comment by wduongf5** [comment]
Thanks for reporting the issue. I've created an internal issue #1345 to track it.

**Comment by shyawnkarim** [comment]
Closing.

TCL iApps have been deprecated. We recommend that you use TS from the Automation Toolchain.
