### ISSUE TITLE
Logs not appearing in OMS

### ISSUE THREAD

**Issue by strtdusty** [F5Networks/f5-cloud-iapps#4]
We have configured the iApp, double checking the wrokspace ID and shared access key.  The components all show up:
![image](https://user-images.githubusercontent.com/1013039/34796951-256e40ae-f60c-11e7-903d-1b72905b349a.png)
The statistics on the "send" iRule indicate that it is being executed without failure:
![image](https://user-images.githubusercontent.com/1013039/34797155-5aef2310-f60c-11e7-8947-2fdec6d25491.png)
I assume I should see a new log schema in OMS.  When searching on "F5CustomLog_CL" as the video indicates,   I see no F5 related schemas:
![image](https://user-images.githubusercontent.com/1013039/34798459-00f0d746-f611-11e7-9c34-d581a5c6afb4.png)
Nothing stands out in the LTM log except maybe:
Jan  9 11:11:57 ourWAF err tmm[40715]: 01010028:3: No members available for pool /Common/Azure-OMS-logger.app/Azure-OMS-logger_format_pool
Jan  9 11:11:57 ourWAF err tmm5[40715]: 01010028:3: No members available for pool /Common/Azure-OMS-logger.app/Azure-OMS-logger_format_pool
Jan  9 11:11:57 ourWAF err tmm4[40715]: 01010028:3: No members available for pool /Common/Azure-OMS-logger.app/Azure-OMS-logger_format_pool
Jan  9 11:11:57 ourWAF err tmm3[40715]: 01010028:3: No members available for pool /Common/Azure-OMS-logger.app/Azure-OMS-logger_format_pool
Jan  9 11:11:57 ourWAF err tmm2[40715]: 01010028:3: No members available for pool /Common/Azure-OMS-logger.app/Azure-OMS-logger_format_pool
Jan  9 11:11:57 ourWAF err tmm7[40715]: 01010028:3: No members available for pool /Common/Azure-OMS-logger.app/Azure-OMS-logger_format_pool
Jan  9 11:11:57 ourWAF err tmm1[40715]: 01010028:3: No members available for pool /Common/Azure-OMS-logger.app/Azure-OMS-logger_format_pool
Jan  9 11:11:57 ourWAF err tmm6[40715]: 01010028:3: No members available for pool /Common/Azure-OMS-logger.app/Azure-OMS-logger_format_pool

**Comment by jsevedge** [comment]
@strtdusty Could you please select 'advanced' in the iApp for the first question about configuration?  Then near the bottom of the iApp select debug for the question "What level of internal logging would you like this solution to use (debug/info during testing)?".  Once done please cause some events to be triggered (ASM violation, etc..) and look at /var/log/ltm for messages around that time and include any relevant ones back here.  

NOTE: Be sure no sensitive information is included in the logs, feel free to switch to the [slack ](https://f5cloudsolutions.herokuapp.com/) channel and send via direct message if you prefer.

**Comment by jsevedge** [comment]
@strtdusty Ah ha, you found a valid bug.  It will be fixed in the next official release, however i have also pushed it to the develop branch so pull the iApp from there and try again in the meantime.  Let me know if it works for you!

https://github.com/F5Networks/f5-cloud-iapps/tree/develop/f5-cloud-logger

**Comment by jsevedge** [comment]
@strtdusty Oh, and once you verify it works remember to go back in and set the logging level to error (maybe info) to stop all the log messages that were generated in debug mode.

**Comment by strtdusty** [comment]
The dev branch fixes our isse.  Thanks!
