### ISSUE TITLE
Pool members not removed when Service Discovery finds no nodes

### ISSUE THREAD

**Issue by simonkowallik** [F5Networks/f5-cloud-iapps#5]
Situation:
1. Service Discovery discovers nodes and adds them to the pool
2. MemberTag=value is removed from all VM instances

The expected result is that the pool is be empty.
Actual result: pool members are not removed.

**Comment by seattlevine** [comment]
This is by design. We want to ensure that should some error occur where the cloud provider returns no members, we do not disrupt service.
