### ISSUE TITLE
Broken HTTP/S monitor with missing Host header

### ISSUE THREAD

**Issue by ArtiomL** [F5Networks/f5-cloud-iapps#7]
Hi,

The iApp doesn't have an option to specify a Host header for the monitor.

HTTP/1.1 based monitors are created with an empty Host header which fails for some apps.

```
GET /monitor.php HTTP/1.1\r\nHost: \r\nConnection: Close\r\n\r\n
```

Thank you!

**Comment by wduongf5** [comment]
Thanks for reporting the issue. I've created an internal issue #1348 to track it.

**Comment by shyawnkarim** [comment]
Closing.

TCL iApps have been deprecated. We recommend using AS3 from the Automation Toolchain.
